### ISSUE TITLE
Update Itembind to 1.20

### ISSUE THREAD

**Issue by RUGMJ** [RedstoneTools/redstonetools-mod#332]

**Comment by RUGMJ** [comment]
when executing the command i want to set this exception occurs

<details>
<summary>Error</summary>

```
[17:28:06] [Render thread/INFO] (Minecraft) [System] [CHAT] §7[§cRST§7]§r Please run any command and hold the item you want the command be bound to
[17:28:12] [Render thread/ERROR] (Minecraft) Reported exception thrown!
net.minecraft.util.crash.CrashException: keyPressed event handler
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:470) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.Keyboard.onKey(Keyboard.java:397) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.Keyboard.method_22678(Keyboard.java:472) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.Keyboard.method_22676(Keyboard.java:472) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:build 13]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:build 13]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:167) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:180) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:285) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1224) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:838) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.ClassCastException: class net.minecraft.client.network.ClientPlayNetworkHandler cannot be cast to class net.minecraft.entity.Entity (net.minecraft.client.network.ClientPlayNetworkHandler and net.minecraft.entity.Entity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6d4b1c02)
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$zla000$redstonetools$injectCommand(ClientPlayNetworkHandler.java:3870) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.sendChatCommand(ClientPlayNetworkHandler.java) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.gui.screen.ChatScreen.sendMessage(ChatScreen.java:244) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.gui.screen.ChatScreen.keyPressed(ChatScreen.java:105) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.Keyboard.method_1454(Keyboard.java:400) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:460) ~[minecraft-merged-06a6aa5ea1-1.20.4-net.fabricmc.yarn.1_20_4.1.20.4+build.3-v2.jar:?]
	... 17 more
```
</details>
